Add build_deploy.sh file
fabric8-analytics/fabric8-analytics-github-refresh-cronjob pull request #60
Opened 2021-08-25 11:00 UTC by mbharatk

`build_deploy.sh` file to be added for app-interface to build and push github-refresh-cronjob images.

2021-08-25 11:24 UTC, sawood14012 requested changes
The Docker file is using the old images please create a new dockerfile or update the dockerfile with using UBI image as base

2021-08-25 11:24 UTC, sawood14012 commented
Rest everything looks fine

2021-08-25 12:39 UTC, sawood14012 requested changes

2021-08-25 12:39 UTC, sawood14012 commented on Dockerfile
> +FROM registry.access.redhat.com/ubi8/python-36:latest
just changing the base image wont work out @mbharatk you might have to manually build and verify or by trial and error method if it works PTAL

2021-08-25 13:11 UTC, rafiu007 reviewed
Please test out the changes before pushing. for this case build out the image and try deploying it.

2021-09-07 08:12 UTC, sawood14012 approved these changes
LGTM (Please merge if it is working on dev cluster)

2021-09-07 08:14 UTC, sawood14012 commented
@mbharatk Please take a look at unit tests

2021-09-07 12:51 UTC, sawood14012 requested changes

2021-09-07 12:51 UTC, sawood14012 commented on qa/runtests.sh
> +        python3 -m pip install --user virtualenv
it is not recommended to install the dependency here as actions already installs it ref: https://github.com/fabric8-analytics/fabric8-analytics-github-refresh-cronjob/blob/master/.github/workflows/ci-build.yml#L40

2021-09-07 14:08 UTC, sawood14012 approved these changes
LGTM

2021-09-07 14:26 UTC, merged